version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: systempulse_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: systempulse
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: systempulse_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: